[package]
name = "reserve-l"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "0.9.0"

[dev_dependencies]
soroban-sdk = { version = "0.9.0", features = ["testutils"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1 